
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 90
#define YY_END_OF_BUFFER 91
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[233] =
    {   0,
        0,    0,   91,   89,    1,    1,   58,   89,   56,   53,
       89,   46,   47,   37,   35,   44,   36,   45,   38,   61,
       43,   39,   54,   42,   55,   50,   34,   40,   41,   52,
       89,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   48,   51,   49,   57,
        1,    0,   71,    0,   64,   76,   72,   81,    0,    0,
       74,   59,    0,   61,   77,   60,   78,    0,   62,    0,
        0,   75,    0,   65,   66,   68,   70,   69,   67,   34,
       34,   34,   82,   34,    0,   34,   34,   34,   34,   34,
       34,    9,   34,   34,   34,   34,   34,   34,   17,   34,

       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       83,   73,    0,   88,   63,    0,   63,   84,    0,    0,
        0,   86,    0,   62,   79,   80,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   15,   34,   18,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,    0,    0,   85,    2,   34,
        4,    5,   34,   34,   34,   34,   11,   12,   34,   34,
       16,   19,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   31,   34,   34,   87,    3,    6,   34,
       34,   34,   34,   14,   34,   34,   22,   34,   34,   34,

       34,   34,   34,   29,   34,   34,   33,   34,   34,   10,
       13,   34,   21,   23,   24,   25,   26,   27,   34,   34,
       34,   34,    8,   34,   28,   34,   34,    7,   20,   30,
       32,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,   24,    1,   25,   25,   25,   25,   26,   25,
       25,   25,   25,   25,   25,   27,   25,   25,   25,   25,
       25,   25,   28,   25,   25,   25,   25,   25,   29,   25,
       30,   31,   32,   33,   34,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   25,   44,   45,   46,   47,
       48,   49,   25,   50,   51,   52,   53,   54,   55,   56,
       57,   58,   59,   60,   61,   62,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[63] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    3,    1,
        1,    1,    1,    1,    1,    1,    1,    4,    1,    1,
        1,    1,    1,    1,    4,    4,    4,    4,    4,    1,
        1,    1,    1,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    1,    1,
        1,    1
    } ;

static yyconst flex_int16_t yy_base[241] =
    {   0,
        0,    0,  447,  592,   61,   64,   64,  412,  395,   62,
      378,  592,  592,  384,   58,  592,   57,   65,   65,   72,
      592,  592,   70,  375,   71,  592,   71,  592,  592,  369,
      346,   78,   79,   82,   84,   81,   88,   86,  101,   91,
      120,  109,  122,  124,  126,  128,  592,   85,  592,  592,
      163,  148,  592,  361,  592,  592,  592,  592,  341,  313,
      592,  592,  299,  162,  592,  592,  592,  280,  129,  280,
      287,  592,  168,  592,  264,  592,  592,  592,  249,    0,
      135,  230,  592,  139,  157,  164,  166,  169,  172,  174,
      175,  176,  177,  178,  184,  179,  196,  199,  201,  204,

      205,  206,  207,  208,  219,  214,  216,  225,  227,  244,
      592,  592,  185,  592,  592,  176,  163,  592,  151,   91,
      147,  592,  131,  103,  592,  592,  226,  245,  249,  255,
      257,  259,  263,  264,  266,  267,  284,  277,  286,  289,
      292,  295,  296,  297,  298,  303,  306,  307,  309,  317,
      318,  310,  321,  328,  330,   96,  187,  592,  336,  339,
      347,  350,  351,  353,  354,  356,  358,  359,  360,  361,
      364,  368,  371,  381,  382,  386,  390,  393,  396,  403,
      394,  401,  405,  408,  411,  423,   92,  425,  426,  431,
      432,  433,  434,  435,  436,  437,  440,  455,  446,  457,

      458,  461,  465,  464,  467,  472,  478,  479,  482,  484,
      487,  489,  490,  491,  493,  499,  501,  502,  504,  508,
      511,  512,  519,  521,  523,  525,  530,  531,  532,  534,
      536,  592,  571,  575,   97,   91,  579,  583,  587,   74
    } ;

static yyconst flex_int16_t yy_def[241] =
    {   0,
      232,    1,  232,  232,  232,  232,  232,  233,  232,  232,
      234,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  235,  232,  232,  232,
      236,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  232,  232,  232,  232,
      232,  232,  232,  233,  232,  232,  232,  232,  232,  237,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  238,
      239,  232,  232,  232,  232,  232,  232,  232,  232,  240,
      235,  235,  232,  235,  236,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,

      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      232,  232,  232,  232,  232,  237,  237,  232,  238,  238,
      239,  232,  232,  232,  232,  232,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  232,  238,  232,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  232,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,

      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,    0,  232,  232,  232,  232,  232,  232,  232,  232
    } ;

static yyconst flex_int16_t yy_nxt[655] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   27,   27,   27,   27,   28,
        4,   29,   30,   31,   32,   33,   34,   35,   36,   37,
       38,   27,   39,   27,   40,   27,   27,   27,   27,   41,
       42,   43,   44,   45,   46,   27,   27,   27,   47,   48,
       49,   50,   51,   51,   51,   51,   51,   51,   52,   57,
       62,   66,   63,   63,   64,   64,   70,   80,   67,   65,
       68,   71,   69,   58,   74,   53,   72,   63,   80,   64,
       75,   76,   78,   79,   84,   80,   80,   73,   80,   80,

       81,   80,  157,   80,   82,   80,  111,  158,   80,  187,
       73,   82,   82,  187,   82,   82,   88,   82,   80,   82,
      124,   82,   91,   89,   82,   93,   80,   94,   87,   90,
       86,   92,   96,   98,   82,   97,   95,   80,  101,   80,
       99,   80,   82,   80,  112,   80,   69,  100,  124,  122,
      103,  104,   80,   82,   73,   82,   80,   82,  102,   82,
      105,   82,  120,  106,   51,   51,   51,   73,   82,  110,
      108,  117,   82,  109,  113,  114,  113,   63,  107,   64,
      123,   80,  123,   80,  117,  124,   80,   73,  156,   80,
       85,   80,   80,   80,   80,   80,   80,   82,  157,   82,

       73,   80,   82,  232,  128,   82,  130,   82,   82,   82,
       82,   82,   82,   80,  132,  127,   80,   82,   80,  129,
      131,   80,   80,   80,   80,   80,  137,  134,  133,   82,
      135,   80,   82,   80,   82,  136,   80,   82,   82,   82,
       82,   82,   80,   80,   80,  138,  142,   82,  145,   82,
      139,  141,   82,  147,  144,  140,  149,  143,   82,   82,
       82,   80,   80,   82,  150,  146,   80,  151,  148,  153,
      126,  154,   80,  159,   80,  152,   80,   82,   82,  160,
       80,   80,   82,   80,   80,  125,  155,  161,   82,  122,
       82,  120,   82,  165,   80,  118,   82,   82,  166,   82,

       82,   80,  167,   80,  162,  169,   80,  163,  164,   80,
       82,  168,   80,   80,   80,   80,   69,   82,  170,   82,
       80,  117,   82,   80,   80,   82,   80,   80,   82,   82,
       82,   82,  172,  171,   80,   80,   82,  173,   80,   82,
       82,  177,   82,   82,  176,   80,  175,   80,  174,  115,
       82,   82,  183,   80,   82,  181,   80,  178,  184,  179,
      180,   82,  185,   82,   80,  182,   55,   80,   80,   82,
       80,   80,   82,   80,  186,   80,   80,   80,   80,   85,
       82,   80,  188,   82,   82,   80,   82,   82,   80,   82,
       83,   82,   82,   82,   82,  190,   77,   82,   80,   80,

      192,   82,  189,   80,   82,   61,  191,   80,   60,  193,
       80,   80,  194,   80,   82,   82,   56,   55,   80,   82,
       80,  195,   80,   82,  198,   80,   82,   82,   80,   82,
      196,  203,  201,  197,   82,  200,   82,  199,   82,  202,
       80,   82,   80,   80,   82,  205,  232,  204,   80,   80,
       80,   80,   80,   80,   80,  232,   82,   80,   82,   82,
      232,  207,  206,   80,   82,   82,   82,   82,   82,   82,
       82,  210,   80,   82,   80,   80,  209,  208,   80,   82,
      211,   80,   80,  213,   80,  215,  232,  212,   82,   80,
       82,   82,  214,  216,   82,   80,   80,   82,   82,   80,

       82,   80,  218,  219,   80,   82,   80,   80,   80,  217,
       80,   82,   82,  220,  221,   82,   80,   82,   80,   80,
       82,   80,   82,   82,   82,   80,   82,  224,   80,   80,
      232,  222,   82,  223,   82,   82,   80,   82,   80,  232,
       80,   82,   80,  225,   82,   82,  226,   80,   80,   80,
      228,   80,   82,   80,   82,  227,   82,  232,   82,  232,
      232,  232,  230,   82,   82,   82,  232,   82,  231,   82,
      229,   54,   54,   54,   54,   59,   59,  232,   59,  116,
      232,  116,  116,  119,  119,  119,  119,  121,  121,  121,
      121,    3,  232,  232,  232,  232,  232,  232,  232,  232,

      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232
    } ;

static yyconst flex_int16_t yy_chk[655] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    5,    5,    5,    6,    6,    6,    7,   10,
       15,   17,   17,   15,   17,   15,   19,  240,   17,   15,
       18,   19,   18,   10,   23,    7,   19,   20,   27,   20,
       23,   23,   25,   25,  236,   32,   33,   20,   36,   34,

      235,   35,  120,   38,   27,   37,   48,  120,   40,  187,
       20,   32,   33,  156,   36,   34,   34,   35,   39,   38,
      124,   37,   35,   34,   40,   36,   42,   36,   33,   34,
       32,   35,   37,   38,   39,   37,   36,   41,   40,   43,
       39,   44,   42,   45,   48,   46,   69,   39,  123,  121,
       42,   42,   81,   41,   69,   43,   84,   44,   41,   45,
       42,   46,  119,   42,   51,   51,   51,   69,   81,   46,
       44,  117,   84,   45,   52,   52,   52,   64,   43,   64,
       73,   86,   73,   87,  116,   73,   88,   64,  113,   89,
       85,   90,   91,   92,   93,   94,   96,   86,  157,   87,

       64,   95,   88,  157,   87,   89,   89,   90,   91,   92,
       93,   94,   96,   97,   91,   86,   98,   95,   99,   88,
       90,  100,  101,  102,  103,  104,   96,   93,   92,   97,
       94,  106,   98,  107,   99,   95,  105,  100,  101,  102,
      103,  104,  108,  127,  109,   97,  102,  106,  104,  107,
       98,  101,  105,  105,  103,  100,  106,  102,  108,  127,
      109,  110,  128,   82,  107,  104,  129,  108,  105,  109,
       79,  109,  130,  127,  131,  108,  132,  110,  128,  128,
      133,  134,  129,  135,  136,   75,  110,  129,  130,   71,
      131,   70,  132,  132,  138,   68,  133,  134,  133,  135,

      136,  137,  134,  139,  130,  136,  140,  131,  131,  141,
      138,  135,  142,  143,  144,  145,   63,  137,  137,  139,
      146,   60,  140,  147,  148,  141,  149,  152,  142,  143,
      144,  145,  141,  139,  150,  151,  146,  142,  153,  147,
      148,  146,  149,  152,  145,  154,  144,  155,  143,   59,
      150,  151,  152,  159,  153,  150,  160,  147,  153,  148,
      149,  154,  154,  155,  161,  151,   54,  162,  163,  159,
      164,  165,  160,  166,  155,  167,  168,  169,  170,   31,
      161,  171,  160,  162,  163,  172,  164,  165,  173,  166,
       30,  167,  168,  169,  170,  164,   24,  171,  174,  175,

      166,  172,  163,  176,  173,   14,  165,  177,   11,  169,
      178,  181,  170,  179,  174,  175,    9,    8,  182,  176,
      180,  173,  183,  177,  176,  184,  178,  181,  185,  179,
      174,  181,  179,  175,  182,  178,  180,  177,  183,  180,
      186,  184,  188,  189,  185,  183,    3,  182,  190,  191,
      192,  193,  194,  195,  196,    0,  186,  197,  188,  189,
        0,  186,  185,  199,  190,  191,  192,  193,  194,  195,
      196,  192,  198,  197,  200,  201,  191,  190,  202,  199,
      193,  204,  203,  196,  205,  199,    0,  195,  198,  206,
      200,  201,  198,  200,  202,  207,  208,  204,  203,  209,

      205,  210,  202,  203,  211,  206,  212,  213,  214,  201,
      215,  207,  208,  205,  206,  209,  216,  210,  217,  218,
      211,  219,  212,  213,  214,  220,  215,  212,  221,  222,
        0,  208,  216,  209,  217,  218,  223,  219,  224,    0,
      225,  220,  226,  219,  221,  222,  220,  227,  228,  229,
      222,  230,  223,  231,  224,  221,  225,    0,  226,    0,
        0,    0,  226,  227,  228,  229,    0,  230,  227,  231,
      224,  233,  233,  233,  233,  234,  234,    0,  234,  237,
        0,  237,  237,  238,  238,  238,  238,  239,  239,  239,
      239,  232,  232,  232,  232,  232,  232,  232,  232,  232,

      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "c_compiler.lex"
/************************************************************************/
/*                                                                      */
/* FILE    : c_compiler.lex                                             */
/* PURPOSE : to cause pain and suffering                                */
/*                                                                      */
/************************************************************************/
#line 10 "c_compiler.lex"
#include <stdio.h>
#include <stdlib.h>
#include "c_compiler_tokens.h"
//#include "symboltable.cpp"

extern int yylval;
extern int lex_debug_level;
extern int symbol_table_debug;
extern int yacc_debug_level;
extern int insert_lookup;
int line = 1;
int column = 0;
FILE *errorText;
char *file_name;
char tmp[80];

void white();
void character();
void mult_line();
void single_line();
void print_error();
void set_debug_level();
void check_int();
int id_token();
void check_float();
/************************************************************************/
/* Regular Definitions                                                  */
/************************************************************************/
#line 716 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 54 "c_compiler.lex"

#line 905 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 233 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 592 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 55 "c_compiler.lex"
{white();}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 58 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("AUTO_tok\n");}return(AUTO_tok);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 62 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("BREAK_tok\n");}return(BREAK_tok);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 66 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("CASE_tok\n");}return(CASE_tok);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 70 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("CHAR_tok\n");}return(CHAR_tok);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 74 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("CONST_tok\n");}return(CONST_tok);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 78 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("CONTINUE_tok\n");}return(CONTINUE_tok);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 82 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("DEFAULT_tok\n");}return(DEFAULT_tok);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 86 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("DO_tok\n");}return(DO_tok);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 90 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("DOUBLE_tok\n");}return(DOUBLE_tok);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 94 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("ELSE_tok\n");}return(ELSE_tok);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 98 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("ENUM_tok\n");}return(ENUM_tok);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 102 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("EXTERN_tok\n");}return(EXTERN_tok);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 106 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("FLOAT_tok\n");}return(FLOAT_tok);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 110 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("FOR_tok\n");}return(FOR_tok);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 114 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("GOTO_tok\n");}return(GOTO_tok);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 118 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("IF_tok\n");}return(IF_tok);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 122 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("INT_tok\n");}return(INT_tok);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 126 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("LONG_tok\n");}return(LONG_tok);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 130 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("REGISTER_tok\n");}return(REGISTER_tok);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 134 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("RETURN_tok\n");}return(RETURN_tok);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 138 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("SHORT_tok\n");}return(SHORT_tok);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 142 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("SIGNED_tok\n");}return(SIGNED_tok);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 146 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("SIZEOF_tok\n");}return(SIZEOF_tok);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 150 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("STATIC_tok\n");}return(STATIC_tok);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 154 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("STRUCT_tok\n");}return(STRUCT_tok);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 158 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("SWITCH_tok\n");}return(SWITCH_tok);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 162 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("TYPEDEF_tok\n");}return(TYPEDEF_tok);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 166 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("UNION_tok\n");}return(UNION_tok);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 170 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("UNSIGNED_tok\n");}return(UNSIGNED_tok);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 174 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("VOID_tok\n");}return(VOID_tok);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 178 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("VOLATILE_tok\n");}return(VOLATILE_tok);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 182 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("WHILE_tok\n");}return(WHILE_tok);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 186 "c_compiler.lex"
{column+=yyleng;return(id_token());}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 188 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("PLUS_tok\n");}return(PLUS_tok);}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 192 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("MINUS_tok\n");}return(MINUS_tok);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 196 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("STAR_tok\n");}return(STAR_tok);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 200 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("DIV_tok\n");}return(DIV_tok);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 204 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("SEMI_tok\n");}return(SEMI_tok);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 208 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("OPEN_BRACKET_tok\n");}return(OPEN_BRACKET_tok);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 212 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("CLOSE_BRACKET_tok\n");}return(CLOSE_BRACKET_tok);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 216 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("EQUAL_tok\n");}return(EQUAL_tok);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 220 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("COLON_tok\n");}return(COLON_tok);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 224 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("COMMA_tok\n");}return(COMMA_tok);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 228 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("PERIOD_tok\n");}return(PERIOD_tok);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 232 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("OPEN_PAREN_tok\n");}return(OPEN_PAREN_tok);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 236 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("CLOSE_PAREN_tok\n");}return(CLOSE_PAREN_tok);}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 240 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("OPEN_BRACE_tok\n");}return(OPEN_BRACE_tok);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 244 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("CLOSE_BRACE_tok\n");}return(CLOSE_BRACE_tok);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 248 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("QUESTION_MARK_tok\n");}return(QUESTION_MARK_tok);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 252 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("BAR_tok\n");}return(BAR_tok);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 256 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("CARET_tok\n");}return(CARET_tok);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 260 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("AMP_tok\n");}return(AMP_tok);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 264 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("GT_tok\n");}return(GT_tok);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 268 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("LT_tok\n");}return(LT_tok);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 272 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("PERCENT_tok\n");}return(PERCENT_tok);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 276 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("TILDA_tok\n");}return(TILDA_tok);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 280 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("NOT_tok\n");}return(NOT_tok);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 284 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("INC_OP_tok\n");}return(INC_OP_tok);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 288 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("DEC_OP_tok\n");}return(DEC_OP_tok);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 292 "c_compiler.lex"
{column+=yyleng;check_int();return(INTEGER_CONSTANT_tok);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 294 "c_compiler.lex"
{column+=yyleng;check_float();return(FLOATING_CONSTANT_tok);}
	YY_BREAK
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
#line 296 "c_compiler.lex"
{column+=yyleng;character();return(CHARACTER_CONSTANT_tok);}
	YY_BREAK
case 64:
/* rule 64 can match eol */
YY_RULE_SETUP
#line 298 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("STRING_LITERAL_tok\n");}return(STRING_LITERAL_tok);}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 303 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("PTR_OP_tok\n");}return(PTR_OP_tok);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 307 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("LEFT_OP_tok\n");}return(LEFT_OP_tok);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 311 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("RIGHT_OP_tok\n");}return(RIGHT_OP_tok);}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 315 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("LE_OP_tok\n");}return(LE_OP_tok);}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 319 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("GE_OP_tok\n");}return(GE_OP_tok);}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 323 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("EQ_OP_tok\n");}return(EQ_OP_tok);}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 327 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("NE_OP_tok\n");}return(NE_OP_tok);}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 331 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("AND_OP_tok\n");}return(AND_OP_tok);}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 335 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("OR_OP_tok\n");}return(OR_OP_tok);}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 339 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("MULT_ASSIGN_tok\n");}return(MULT_ASSIGN_tok);}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 343 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("DIV_ASSIGN_tok\n");}return(DIV_ASSIGN_tok);}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 347 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("MOD_ASSIGN_tok\n");}return(MOD_ASSIGN_tok);}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 351 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("ADD_ASSIGN_tok\n");}return(ADD_ASSIGN_tok);}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 355 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("SUB_ASSIGN_tok\n");}return(SUB_ASSIGN_tok);}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 359 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("LEFT_ASSIGN_tok\n");}return(LEFT_ASSIGN_tok);}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 363 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("RIGHT_ASSIGN_tok\n");}return(RIGHT_ASSIGN_tok);}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 367 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("AND_ASSIGN_tok\n");}return(AND_ASSIGN_tok);}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 371 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("XOR_ASSIGN_tok\n");}return(XOR_ASSIGN_tok);}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 375 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("OR_ASSIGN_tok\n");}return(OR_ASSIGN_tok);}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 379 "c_compiler.lex"
{column+=yyleng;if(lex_debug_level%5==0){
			printf("%s ==>",yytext);}if(lex_debug_level%2==0){
			printf("ELIPSIS_tok\n");}return(ELIPSIS_tok);}
	YY_BREAK
case 85:
/* rule 85 can match eol */
YY_RULE_SETUP
#line 383 "c_compiler.lex"
{mult_line();}
	YY_BREAK
case 86:
/* rule 86 can match eol */
YY_RULE_SETUP
#line 385 "c_compiler.lex"
{single_line();}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 387 "c_compiler.lex"
{set_debug_level();}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 389 "c_compiler.lex"
{column+=yyleng; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 391 "c_compiler.lex"
{column+=yyleng;print_error("Syntax Error: Not Legal Character.");
				return(ERROR_tok);}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 396 "c_compiler.lex"
ECHO;
	YY_BREAK
#line 1602 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 233 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 233 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 232);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 396 "c_compiler.lex"


void white()
{
	//printf("S%sN",yytext);
	for(int i =0;i<yyleng;i++)
	{
		//count the lines and columns for errors
		if(yytext[i]=='\t')
		{
			//printf("char == tab \n");
			column += 7;
		}
		else if(yytext[i]=='\n')
		{
			//printf("char == new line\n");
			fgets(tmp,sizeof tmp, errorText);
			//printf("%s",tmp);
			line ++;
			//printf("columns %d\n",column);
			column = 0;
			//printf("Lines = %d, Column = %d\n",line,column);
		}
		else if(yytext[i]==' ')
		{
			//printf("char == space\n");
			column +=1;
		}
	}
	
}

void character()
{
	int code = 0;
	if(lex_debug_level%5==0)
	{
		printf("%s ==>",yytext);
	}
		
	if(lex_debug_level%2==0)
	{
		printf("CHARACTER_CONSTANT_tok\n");
	}
	
	if(yytext[1]!='\\' && yytext[1]!='\'')
	{
		yylval = yytext[1];
	}
	else if(yytext[1]=='\\')
	{
		switch(yytext[2])
		{
			case 'n':
				yylval = 10;
				break;
			case 't':
				yylval = 9;
				break;
			case 'v':
				yylval = 11;
				break;
			case 'b':
				yylval = 8;
				break;
			case 'r':
				yylval = 13;
				break;
			case 'f':
				yylval = 12;
				break;
			case 'a':
				yylval = 7;
				break;
			case '\\':
				yylval = 92;
				break;
			case '\?':
				yylval = 63;
				break;
			case '\'':
				yylval = 39;
				break;
			case '\"':
				yylval = 34;
				break;
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
				for(int j = 2; j<5 ;j++)
				{
					//printf("%d\t%d\n",yytext[j],j);
					if(!(yytext[j]>=48 && yytext[j]<56))
					{
						print_error("Octal character error.");
					}
					else
					{
						code = (code * 8) + (yytext[j] - 48);
					}
				}
				if(code>127)
				{
					print_error("Octal character out of range.");
				}
				//printf("%d",code);
				yylval = code;
				break;
			case 'x':
				for(int j = 3; j<5 ;j++)
				{
					if((yytext[j]>=48 && yytext[j]<58))
					{
						code = (code * 16) + (yytext[j] - 48);
					}
					else if((yytext[j]>=65 && yytext[j]<71))
					{
						code = (code * 16) + (yytext[j] - 55);
					}
					else
					{
						print_error("Hex character error.");
					}
				}
				if(code>127)
				{
					print_error("Hex character out of range.");
				}
				//printf("%d",code);
				yylval = code;
				break;

			//hex 7F octal 177 max limit
		}
	}
	printf("%c\t%d\n",yylval,yylval);
	//checks valid chars and reports error 
	
}

void mult_line()
{
	
	//printf("%u\n",yyleng);
	for(int i=0;i<yyleng;i++)
	{
		//printf("%c",yytext[i]);
		if(yytext[i]=='\n')
		{
			fgets(tmp,sizeof tmp, errorText);
			line ++;
			//printf("columns %d\n",column);
			column = 0;
		}
	}
}

void single_line()
{
	
	fgets(tmp,sizeof tmp, errorText);
	line++;
	//printf("columns %d\n",column);
	column = 0;
}

void print_error(char *error_msg)
{	long int offset = ftell(errorText);
	fgets(tmp,sizeof tmp, errorText);
	fseek(errorText,offset,SEEK_SET);
	printf("ERROR: %s:Line: %d Column: %d %s\n",file_name,line,column,error_msg);
	printf("%s",tmp);
	for(int i = column; i>0;i--)
	{
		printf("-");
	}
	printf("^ \n\n");
	//printf("columns %d, lines %d\n",column,line);
}

void set_debug_level()
{
	//printf("set Debug");
	column+=yyleng;
	
	//char* stringFrom = yytext+'\n';
	char typebug='L';
	char num[4];
	int level=0;
	//printf("%s\n",yytext);
	typebug = yytext[2];
	for(int i = 0; i < 4; i++)
	{
		num[i]=yytext[i+4];
	}
	level = atoi(num);
	//sscanf(yytext+'\n',"!!%c %d",&typebug,&level);
	//printf("Debug %c set to %d\n",typebug,level);
	if(typebug == 'Y')
	{
		yacc_debug_level = level;
	}
	else
	{
		lex_debug_level = level;
	}
}

void check_int()
{
	if(lex_debug_level%5==0)
	{
		printf("%s ==>",yytext);
	}
		
	if(lex_debug_level%2==0)
	{
		printf("INTEGER_CONSTANT_tok\n");
	}
	
	long int test_int_down = -2147483648;
	long int test_int_up = 2147483647;
	long int test = atol(yytext);
	
	//printf("Up %ld, Down %ld, Given %ld\n",test_int_up,test_int_down,test);
	
	if(test<test_int_down || test > test_int_up)
	{
		print_error("Syntax Error: Int Value Out Of Range.");
	}
	
	//printf("%d",yylval);
	yylval = test;
	//return INTEGER_CONSTANT_tok;
	
}

void check_float()
{
	if(lex_debug_level%5==0)
	{
		printf("%s ==>",yytext);
	}
		
	if(lex_debug_level%2==0)
	{
		printf("FLOATING_CONSTANT_tok\n");
	}
	//print_error("Float Value Too Large.");
}

int id_token()
{
	// pointsTo = NULL;
	// pointsTo = s.searchAll(yytext);
	// if(pointsTo.ntype == 1)
	// {
	// 	yylval = pointsTo;
	// 	return(ID_tok);
	// }
	// else if(pointsTo.ntype==2)
	// {
	// 	yylval = pointsTo;
	// 	return(ENUMERATION_CONSTANT_tok);
	// }
	// else if(pointsTo.ntype == 3)
	// {
	// 	yylval = pointsTo;
	// 	return(TYPEDEF_NAME_tok);
	// }
	// else
	// {
	// 	yylval = s.insert(yytext);
	// 	return(ID_tok);
	// }
	if(lex_debug_level%5==0)
	{
		printf("%s ==>",yytext);
	}
	if(lex_debug_level%2==0)
	{
		printf("ID_tok\n");
	}
	return(ID_tok);
}

int main(int argc, char **argv)
{
	if(argc==1)
	{
		printf("No File Provided. Pass file in command line.");
	}
	else
	{
		if(!(yyin=fopen(argv[argc-1],"r")))
		{
			perror(argv[argc-1]);
			return(1);
		}
		file_name=argv[argc-1];
		errorText = fopen(argv[argc-1],"r");
		for(int i=argc-1; i>=1; i--)
		{
			//add to debug levels
			
		}
	}
	int tok;
	//SymbolTable s;
	//s.insert("KEY",Data);
	//s.pushEmptyBST();
	//s.popBST();
	//s.searchTop("KEY");//returns pointer to node
	//s.searchAll("KEY");//returns pointer
	//s.writeToFile();//dumps table to file
	lex_debug_level = 1;
	symbol_table_debug = 1;
	yacc_debug_level = 1;
	while((tok = yylex()))
	{
	
		//printf("%d\n",tok);
	}
	return 0;	
}
